apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: true
        jsonData:
          maxLines: 500
          timeout: 120
        withCredentials: false
        basicAuth: false
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provision
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards