apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      http_server_read_timeout: 300s   # Erhöht für Timeouts
      http_server_write_timeout: 300s  # Erhöht für Timeouts

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0
      wal:
        enabled: true
        dir: /tmp/loki/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 32        # Sehr großzügig
      ingestion_burst_size_mb: 64  # Sehr großzügig
      per_stream_rate_limit: 16MB  # Großzügigeres Limit
      per_stream_rate_limit_burst: 32MB 
      max_global_streams_per_user: 15000
      max_query_series: 1500
      max_query_parallelism: 32
      cardinality_limit: 150000
      max_streams_per_user: 15000
      max_line_size: 1MB        # Erhöht von 512KB
      split_queries_by_interval: 15m  
      query_timeout: 5m         # Längeres Timeout für Abfragen

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /tmp/loki/chunks

    compactor:
      working_directory: /tmp/loki/compactor
      shared_store: filesystem

    chunk_store_config:
      max_look_back_period: 48h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 48h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 2048     # Größerer Cache
            validity: 24h

    frontend:
      compress_responses: true
      log_queries_longer_than: 10s
      downstream_url: http://localhost:3100