apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-loki-dirs
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          mkdir -p /tmp/loki/chunks /tmp/loki/index /tmp/loki/index_cache /tmp/loki/rules
          chmod -R 777 /tmp/loki
        volumeMounts:
        - name: storage
          mountPath: /tmp/loki
      containers:
      - name: loki
        image: grafana/loki:2.5.0  # Ältere Version verwenden
        args:
        - -config.file=/etc/loki/loki-config.yaml
        - -target=all
        ports:
        - containerPort: 3100
          name: http-metrics
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 10001  # Loki-Standardbenutzer
          runAsGroup: 10001
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /tmp/loki
      volumes:
      - name: storage
        emptyDir: {}
      - name: config
        configMap:
          name: loki-config

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    name: http-metrics
  type: ClusterIP