apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push
        tenant_id: "default"
        batchwait: 1s
        batchsize: 1048576  # 1MB
        backoff_config:
          min_period: 500ms
          max_period: 5m
          max_retries: 10

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod_name
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container_name
        pipeline_stages:
          - docker: {}
          # Filter für Backend-Logs: Kategorisiere nach Log-Level
          - match:
              selector: '{container_name="backend"}'
              stages:
                - regex:
                    expression: '\\[(debug|info|warn|error)\\]'
                - labels:
                    level:
          # Filter für andere Container: Nur Fehler-Logs erfassen
          - match:
              selector: '{container_name!="backend"}'
              stages:
                - regex:
                    expression: '.*(error|Error|ERROR|exception|Exception|EXCEPTION|fail|Fail|FAIL).*'
                    source: message
        static_configs:
          - targets:
              - localhost
            labels:
              job: docker-logs
              __path__: /var/lib/docker/containers/*/*.log